 <?php foreach ($this->getProducts() as $k => $data): 
          $product  = $data['product'];   
          $licenses = $data['licenses'];
 ?>
     <table cellspacing="0" cellpadding="0" border="0" width="650">
        <thead>
            <tr>
                <th align="left" width="325" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;"><?php echo $product->getName(); ?></th>
            </tr>
        </thead>
        <tbody>
    <?php foreach ($licenses as $license): ?>
        <tr>
            <td valign="top" style="font-size:12px; padding:7px 9px 9px 9px; border-left:1px solid #EAEAEA; border-bottom:1px solid #EAEAEA; border-right:1px solid #EAEAEA;">
                <?php echo $license; ?>
            </td>
        </tr>
    <?php endforeach; ?>
        </tbody>
    </table>
<?php endforeach; ?>